name: docs

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/__tests__/**'
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    env:
      DOCS_GA_ID: G-CTB8FQ7VMW
      NODE_VERSION: '18'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Handle yarn cache
        uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-node-${{ env.NODE_VERSION }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ env.NODE_VERSION }}-yarn-
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build documentation site
        run: yarn docs:build

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          # repo: liubz/liubz.github.io
          target_branch: gh-pages
          build_dir: docs/.vitepress/dist/
        env:
          GH_PAT: ${{ secrets.ACCESS_TOKEN }}
